### PR TITLE
[ci skip] [cf admin skip] ***NO_CI*** Add `automerge`/`update-grayskull`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Hi @synapticarbors :wave:,
I feel like I'm not pulling my weight on this repo so I thought I might put in a PR to minimise the maintenance overhead.

With `inspection: update-grayskull` I think `automerge` works pretty well. If you'd prefer to continue doing the due-diligence manually, that's totally fine - feel free to close this PR.

**Comment by synapticarbors** [comment]
I haven't used this the `inspect` feature before. I've always been a bit hesitant to use automerge, but will look into the feature. I think for now though, I'll continue manually inspecting this one since it's such a popular and widely used package.

**Comment by dhirschfeld** [comment]
> I haven't used this the `inspect` feature before. I've always been a bit hesitant to use automerge, but will look into the feature.

I was very anti-automerge before the `update-grayskull` option - it just published broken packages all the time. With `grayskull` it knows how to also bump the dependencies and I've found it very robust (haven't seen it make a mistake).

**Comment by dhirschfeld** [comment]
I removed `automerge` so it still needs to be manually merged. It might be an idea to keep the `update-grayskull` so any dependency changes are picked up automatically. You'll still probably want to do your due-diligence but it might help with that.

Totally fine to leave things as they are if you think that's best though?

**Comment by synapticarbors** [comment]
Let's give this a try without the automerge. I'm curious to see what the `update-greyskull` picks up since I haven't used it on any of the feedstocks I maintain.

**Comment by synapticarbors** [comment]
And thanks for introducing this to me. I guess I'm not fully up on all of the innovations that haven't been elevated to a default setting.

**Comment by dhirschfeld** [comment]
> I'm curious to see what the `update-greyskull` picks up since I haven't used it on any of the feedstocks I maintain.

We just need to wait for an upstream dependency change to watch it do it's magic! 😄

**Pull request merged**
